kind: Deployment
apiVersion: apps/v1
metadata:
  name: edufami-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edufami-app
  template:
    metadata:
      labels:
        app: edufami-app
    spec:
      containers:
        - name: edufami-app
          image: localhost:5000/edufami-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always